---------------------------------------------
-- DML: com_m_timezone (タイムゾーンマスタ) 登録データ
-- 前提: DDL/table/com_m_timezone.sql の実行が完了していること。
-- 冪等性のため、既存行は ON CONFLICT で上書き更新する。
---------------------------------------------
INSERT INTO public.com_m_timezone (timezone, display_name_ja, display_name_en, sort_no) VALUES
  ('Asia/Tokyo', '日本（東京）', 'Japan (Tokyo)', 1),
  ('America/Toronto', 'カナダ東部（トロント）', 'Canada Eastern (Toronto)', 2),
  ('America/Winnipeg', 'カナダ中部（ウィニペグ）', 'Canada Central (Winnipeg)', 3),
  ('America/Edmonton', 'カナダ山岳部（エドモントン）', 'Canada Mountain (Edmonton)', 4),
  ('America/Vancouver', 'カナダ太平洋（バンクーバー）', 'Canada Pacific (Vancouver)', 5),
  ('America/Halifax', 'カナダ大西洋岸（ハリファックス）', 'Canada Atlantic (Halifax)', 6),
  ('America/St_Johns', 'カナダ・ニューファンドランド（セントジョンズ）', 'Canada Newfoundland (St. John''s)', 7),
  ('America/New_York', 'アメリカ東部（ニューヨーク）', 'US Eastern (New York)', 8),
  ('America/Chicago', 'アメリカ中部（シカゴ）', 'US Central (Chicago)', 9),
  ('America/Denver', 'アメリカ山岳部（デンバー）', 'US Mountain (Denver)', 10),
  ('America/Los_Angeles', 'アメリカ太平洋（ロサンゼルス）', 'US Pacific (Los Angeles)', 11),
  ('America/Phoenix', 'アメリカ山岳部（フェニックス・DSTなし）', 'US Mountain (Phoenix, No DST)', 12),
  ('America/Anchorage', 'アラスカ（アンカレッジ）', 'Alaska (Anchorage)', 13),
  ('Pacific/Honolulu', 'ハワイ（ホノルル）', 'Hawaii (Honolulu)', 14),
  ('America/Puerto_Rico', 'プエルトリコ', 'Puerto Rico', 15),
  ('America/Jamaica', 'ジャマイカ', 'Jamaica', 16),
  ('America/Sao_Paulo', 'ブラジル（サンパウロ）', 'Brazil (São Paulo)', 17),
  ('America/Argentina/Buenos_Aires', 'アルゼンチン（ブエノスアイレス）', 'Argentina (Buenos Aires)', 18),
  ('America/Bogota', 'コロンビア（ボゴタ）', 'Colombia (Bogotá)', 19),
  ('Europe/London', 'イギリス（ロンドン）', 'United Kingdom (London)', 20),
  ('Europe/Lisbon', 'ポルトガル（リスボン）', 'Portugal (Lisbon)', 21),
  ('Atlantic/Reykjavik', 'アイスランド（レイキャビク）', 'Iceland (Reykjavik)', 22),
  ('Europe/Berlin', '中央ヨーロッパ（ベルリン）', 'Central Europe (Berlin)', 23),
  ('Europe/Athens', '東ヨーロッパ（アテネ）', 'Eastern Europe (Athens)', 24),
  ('Africa/Cairo', 'エジプト（カイロ）', 'Egypt (Cairo)', 25),
  ('Africa/Harare', '中央アフリカ（ハラレ）', 'Central Africa (Harare)', 26),
  ('Africa/Nairobi', '東アフリカ（ナイロビ）', 'East Africa (Nairobi)', 27),
  ('Asia/Riyadh', 'サウジアラビア（リヤド）', 'Saudi Arabia (Riyadh)', 28),
  ('Asia/Dubai', 'UAE（ドバイ）', 'UAE (Dubai)', 29),
  ('Asia/Tehran', 'イラン（テヘラン）', 'Iran (Tehran)', 30),
  ('Asia/Yerevan', 'アルメニア（エレバン）', 'Armenia (Yerevan)', 31),
  ('Asia/Kolkata', 'インド（コルカタ）', 'India (Kolkata)', 32),
  ('Asia/Dhaka', 'バングラデシュ（ダッカ）', 'Bangladesh (Dhaka)', 33),
  ('Asia/Karachi', 'パキスタン（カラチ）', 'Pakistan (Karachi)', 34),
  ('Asia/Taipei', '台湾（台北）', 'Taiwan (Taipei)', 35),
  ('Asia/Seoul', '韓国（ソウル）', 'Korea (Seoul)', 36),
  ('Asia/Singapore', 'シンガポール', 'Singapore', 37),
  ('Asia/Jakarta', 'インドネシア西部（ジャカルタ）', 'Indonesia Western (Jakarta)', 38),
  ('Asia/Makassar', 'インドネシア中部（マカッサル）', 'Indonesia Central (Makassar)', 39),
  ('Asia/Jayapura', 'インドネシア東部（ジャヤプラ）', 'Indonesia Eastern (Jayapura)', 40),
  ('Asia/Phnom_Penh', 'カンボジア（プノンペン）', 'Cambodia (Phnom Penh)', 41),
  ('Asia/Ho_Chi_Minh', 'ベトナム（ホーチミン）', 'Vietnam (Ho Chi Minh City)', 42),
  ('Australia/Perth', 'オーストラリア西部（パース）', 'Australia Western (Perth)', 43),
  ('Australia/Adelaide', 'オーストラリア中部（アデレード）', 'Australia Central (Adelaide)', 44),
  ('Australia/Darwin', 'オーストラリア中部（ダーウィン・DSTなし）', 'Australia Central (Darwin, No DST)', 45),
  ('Australia/Brisbane', 'オーストラリア東部（ブリスベン・DSTなし）', 'Australia Eastern (Brisbane, No DST)', 46),
  ('Australia/Sydney', 'オーストラリア東部（シドニー）', 'Australia Eastern (Sydney)', 47),
  ('Pacific/Auckland', 'ニュージーランド（オークランド）', 'New Zealand (Auckland)', 48),
  ('Pacific/Guadalcanal', 'ソロモン諸島', 'Solomon Islands', 49),
  ('Pacific/Midway', 'ミッドウェー諸島', 'Midway Islands', 50)
ON CONFLICT (timezone) DO UPDATE SET
  display_name_ja = EXCLUDED.display_name_ja,
  display_name_en = EXCLUDED.display_name_en,
  sort_no = EXCLUDED.sort_no,
  update_date = now();
