---------------------------------------------
-- 【廃止 (2026-09-11)】本関数は削除した。
---------------------------------------------
-- 「振替」という、既存セッションの日時をその場で変更する独立概念を廃止し、
-- 個別セッションの扱いを「キャンセル（候補提案は任意・最大3件）」「予約（承認制）」の
-- 2パターンに単純化する方針としたため。振替に相当する操作は、
--   1. cancel_session() でキャンセルする（必要なら候補時間を提案できる。coach_id/
--      student_idどちらの当事者からも可能。proposed_by_roleで方向を記録）
--   2. 返還されたチケットに対して create_session_booking_request() で新規予約を
--      リクエストし、コーチの承認(approve_session_booking_request)を得る
--      （または cancel_session() 提案済みの候補を accept_session_reschedule_proposal()
--      で承諾する）
-- という2ステップに置き換わる。上記2の各RPCも、元セッションを直接更新せず新規行を
-- 作成しrescheduled_fromで元の行を参照する点は本関数の設計を踏襲するが、元セッションの
-- ステータスはcancel_session()が確定させたcancelled_by_student(3)/cancelled_by_coach(4)の
-- ままとなり、本関数が使っていたrescheduled(5)は新規には発生しなくなる。
-- status=5(rescheduled)の値自体は、過去に本関数で作成された履歴データのため
-- com_t_session.chk_session_status からは削除しない。
---------------------------------------------
DROP FUNCTION IF EXISTS public.reschedule_session(uuid, date, time, text);
